# Defaults for properties available during build execution
# These can be overriden in pipeline build data file or in the pipeline run parameters.
#
# Property priority resolution order:
# 1. Jenkins Environment
# 2. Shared library Build Properties Defaults
# 3. Build Properties Defaults (this file)
# 4. Build Data File
# 5. Pipeline Run Parameters
# 6. OVERRIDE_PARAMS param

# Build Tools
JENKINS_ANT_FOR_BUILDS: ant-auto
JENKINS_JDK_FOR_BUILDS: Java8_auto
JENKINS_MAVEN_FOR_BUILDS: maven3-auto
JENKINS_GRADLE_FOR_BUILDS: gradle-auto

# Maven
MAVEN_RESOLVE_REPO_URL: http://orl-jfrog-lb.pentaho.net/artifactory/pntprv-mvn
MAVEN_TEST_OPTS: -DsurefireArgLine=-Xmx1g
MAVEN_SETTINGS: ${BUILD_CONFIG_ROOT_PATH}/maven/settings.xml

# Stage execution
RUN_STAGE_CHECKOUT  : true
RUN_STAGE_VERSION   : false
RUN_STAGE_BUILD     : true
RUN_STAGE_TEST      : true
RUN_STAGE_TAG       : false
RUN_STAGE_PUSH      : false
RUN_STAGE_ARCHIVE   : true
RUN_STAGE_REPORT    : true

# General
NOOP: false
BUILD_RETRIES: 1
BUILD_TIMEOUT: 360
SLAVE_NODE_LABEL: non-master
ARTIFACT_DEPLOYER_CREDENTIALS_ID: nexus-buildguy
BUILD_ORDER_REPORT: false

# SCM
SCM_CREDENTIALS_ID: github-buildguy
DEFAULT_BRANCH: master

# Version control properties
RELEASE_BUILD_NUMBER: ${BUILD_NUMBER}
RELEASE_VERSION: 9.0.0.1
DEPLOYMENT_FOLDER: 9.0.0.1
BUILD_ID_TAIL: -${RELEASE_BUILD_NUMBER}
RELEASE_MODE: false

# Tagging
TAG_NAME: ${RELEASE_VERSION}-RC
TAG_MESSAGE: Tag created by ${JOB_NAME} ${BUILD_NUMBER}
TICKET_MANAGER_URL: 'https://jira.pentaho.com/browse'

# Skip tagging if the RELEASE_VERSION is a SNAPSHOT
TAG_SKIP_SNAPSHOT: true

# Slack Integration
SLACK_INTEGRATION: false
SLACK_CHANNEL: 'slack-channel-name'
SLACK_TEAM_DOMAIN: 'hitachivantara-eng'
SLACK_CREDENTIALS_ID: 'slack-token'

# Security parameters
RUN_NEXUS_LIFECYCLE: false
RUN_DEPENDENCY_CHECK: false
VULNERABILITY_DATABASE_PATH: '/build/security/national-vulnerability-database'
DEPENDENCY_CHECK_SUPPRESSION_PATH: '/home/buildguy/suppress.xml'

# Docker
DOCKER_IMAGE_HOST: pntprv-docker-release.orl-jfrog-lb.pentaho.net
DOCKER_REGISTRY_URL: http://pntprv-docker-release.orl-jfrog-lb.pentaho.net

# Minions
MINION_PIPELINE_TEMPLATE: resources/templates/minion-pipeline-default.vm